language: cpp

compiler:
  - gcc
  - clang

install:
  # c++ 4.8 lib
  - sudo apt-get install --allow-unauthenticated -qq libstdc++-4.8-dev

  # gloox 8
  - sudo apt-get install --allow-unauthenticated -qq libgloox-dev

script: make

os:
  - linux

