#ifndef DYNAMIC_HPP
#define	DYNAMIC_HPP


#include "Objects/Alive.hpp"
#include "Objects/Behavior/BasicInteraction.hpp"
#include "Objects/Behavior/Behavior.hpp"
#include "Objects/Crafter.hpp"
#include "Objects/Creature.hpp"
#include "Objects/Door.hpp"
#include "Objects/Human.hpp"
#include "Objects/Interactive.hpp"
#include "Objects/Inventory.hpp"
#include "Objects/Item.hpp"
#include "Objects/Location.hpp"
#include "Objects/Potion.hpp"
#include "Objects/Resource.hpp"
#include "Objects/SpellScroll.hpp"
#include "Objects/Spells/HealingSpell.hpp"
#include "Objects/Spells/Spell.hpp"
#include "Objects/Spells/TeleportSpell.hpp"
#include "Objects/ThorsHammer.hpp"
#include "Objects/Traps/AttackTrap.hpp"
#include "Objects/Traps/DoorLock.hpp"
#include "Objects/Traps/HardcoreRespawn.hpp"
#include "Objects/Traps/Healing.hpp"
#include "Objects/Traps/ItemRespawner.hpp"
#include "Objects/Traps/MTATrap.hpp"
#include "Objects/Traps/SimpleDamageTrap.hpp"
#include "Objects/Traps/Trap.hpp"
#include "Objects/Virtual/Base.hpp"
#include "Objects/Virtual/Dropper.hpp"
#include "Objects/Virtual/IDescriptable.hpp"
#include "Objects/Virtual/Recipe.hpp"
#include "Objects/Virtual/Stats.hpp"
#include "Objects/Wearable.hpp"
#endif
